### ISSUE TITLE
Redundancy bus - Manuel utilisateur - vFr2.pdf/corrections

### ISSUE THREAD

**Issue by mipel85** [Ceeb182/Nonofficial_frsky_doc#14]
version sans édition du texte corrigé avec Master PDF Editor 4.
[Redundancy bus - Manuel utilisateur - vFr2.pdf](https://github.com/Ceeb182/Nonofficial_frsky_doc/files/1424103/Redundancy.bus.-.Manuel.utilisateur.-.vFr2.pdf)

**Comment by Ceeb182** [comment]
I'll start correcting tonight.

**Comment by Ceeb182** [comment]
Voici le fichier corrigé / Here is the corrected file
[Redundancy bus - Manuel utilisateur - vFr3.pdf](https://github.com/Ceeb182/Nonofficial_frsky_doc/files/1424578/Redundancy.bus.-.Manuel.utilisateur.-.vFr3.pdf)

Note de version / Release note :
**Section en Français**
>- Section "Caractéristiques" :
>   * orthographe : "Caractéri**s**tiques", "gr**â**ce", 2x "rafra**î**chissement", "param**é**trable" 
>   * grammaire : "Compatible" sans "s"
>- Section "Connexion" : 2x expression "qu'un" en "d'un"
>- Section "Alimentation électrique" : grammaire : 2x "si **les** tension**s** des sources d'alimentations **sont**"
>- Section "Protection contre les surcharges" : orthographe 4x "ambi**a**nt", "ambi**a**nte", "recomm**a**ndé"
>- Section "Configurer la période du signal de sortie des Servos" : orthographe 2x "branché**e**"

**English section** 
>- "Caractéristiques" section :
>   * spelling : "Caractéri**s**tiques", "gr**â**ce", 2x "rafra**î**chissement", "param**é**trable" 
>   * grammar : "Compatible" without "s"
>- "Connexion" section : 2x expression "qu'un" into "d'un"
>- "Alimentation électrique" section : grammar : 2x "si **les** tension**s** des sources d'alimentations **sont**"
>- "Protection contre les surcharges" section : spelling 4x "ambi**a**nt", "ambi**a**nte", "recomm**a**ndé"
>- "Configurer la période du signal de sortie des Servos" section : spelling 2x "branché**e**"

@mipel85 Je pense avoir tout corrigé. Peux-tu faire une vérification rapide ?
@mipel85 I think I have corrected everything. Can you do a quick check ?

**Comment by mipel85** [comment]
good for me on vFr3 version

**Comment by Ceeb182** [comment]
Thanks.
Work merged on **Next_release** branch.
