### ISSUE TITLE
Receiver - S6R S8R / New FR translation in "Base" version 

### ISSUE THREAD

**Issue by Ceeb182** [Ceeb182/Nonofficial_frsky_doc#16]
- [x] New Literal translation

I begin to work on new French translation in "**Base**" version of S6R/S8R receiver.
I use "**S6RS8R - User manual vEN 2017-01-09.pdf**" as origin from https://www.frsky-rc.com.

**Comment by Ceeb182** [comment]
**FR** / @mipel85 
Voici la traduction FR du manuel des récepteurs S6R S8R.
Peux-tu vérifier que tout est ok ?

**EN** / @mipel85 
Here is the FR translation of the S6R S8R receiver manual.
Can you check that everything is ok?

[S6R S8R - Manuel utilisateur - vFr1.pdf](https://github.com/Ceeb182/Nonofficial_frsky_doc/files/1489101/S6R.S8R.-.Manuel.utilisateur.-.vFr1.pdf)

**Comment by Ceeb182** [comment]
@phil-86, you can check the file too

**Comment by phil-86** [comment]
[S6R.S8R.-.Manuel.utilisateur.-.vFr1-phil86.pdf](https://github.com/Ceeb182/Nonofficial_frsky_doc/files/1502112/S6R.S8R.-.Manuel.utilisateur.-.vFr1-phil86.pdf)

**Comment by Ceeb182** [comment]
**FR** 
- Pour la notation "100mA@5V", je la laisse ainsi car c'est la notation adoptée dans toutes les documentations FrSky  
- Pour l'erreur en page 2, je la corrige dans le prochain Commit  

**EN**
- For the notation "100mA@5V", I leave it as it is the notation adopted in all FrSky documentations  
- For the error on page 2, I correct it in the next Commit

**Comment by Ceeb182** [comment]
Voici le fichier corrigé / Here is the corrected file
[S6R S8R - Manuel utilisateur - vFr1.pdf](https://github.com/Ceeb182/Nonofficial_frsky_doc/raw/Ceeb182/S6RS8R_FR_BASE/Working_folder/Receiver%20-%20S6R%20S8R/S6R%20S8R%20-%20Release/FR/S6R%20S8R%20-%20Manuel%20utilisateur%20-%20vFr1.pdf)

Note de version / Release note :

**Section en français**
>Correction du manuel vBase des récepteur S6R/S8R
>- Section "Caractéristique" : orthographe de "Caractéri**s**tique"
>- Section "Fonction" : grammaire "ces types de modèle**s**"
>- Section "Réglage du gain" : grammaire "peut être réalis**é**"
>- Section "Calibration de l'accéléromètre" : 
>   * orthographe "éno**n**cée"
>   * expression "pensez à appuyer"
>- Section "vérification du sens des gouvernes" : grammaire "illustré"
>- Note à la fin du document : grammaire "Pour tirer part**i**"

**English section**
>S6R / S8R receiver vBase manual correction
>- "Caractéristique" section : spelling "Caractéri**s**tique"
>- "Fonction" section : grammar "ces types de modèle**s**"
>- "Réglage du gain" section : grammar "peut être réalis**é**"
>- "Calibration de l'accéléromètre" section : 
>   * spelling "éno**n**cée"
>   * expression "pensez à appuyer"
>- "vérification du sens des gouvernes" section : grammar "illustré"
>- Note at the end of document : grammar "Pour tirer part**i**"

Thanks @mipel85 for checking this document.
**FR /** Je pense avoir tout corrigé. Peux-tu faire une vérification rapide ?
Si c'est Ok laisse quand même ouvert l'issue #16. Je la fermerai quand j'effectuerai le MERGE de la correction.
**EN /** I think I have corrected everything. Can you do a quick check ?
If it's Ok let's still open issue #16. I will close it when I perform the MERGE of the fix.

**Comment by phil-86** [comment]
Je viens de relire et tout me semble bien.
A+
phil-86

**Comment by Ceeb182** [comment]
Ok bien reçu ! 
A+ 
Ceeb182 


----- Mail original -----

De: "phil-86" <notifications@github.com> 
À: "Ceeb182/Nonofficial_frsky_doc" <Nonofficial_frsky_doc@noreply.github.com> 
Cc: "Celestin EBRARD" <ceeb182@laposte.net>, "Assign" <assign@noreply.github.com> 
Envoyé: Dimanche 26 Novembre 2017 19:22:33 
Objet: Re: [Ceeb182/Nonofficial_frsky_doc] Receiver - S6R S8R / New FR translation in "Base" version (#16) 



Je viens de relire et tout me semble bien. 
A+ 
phil-86

**Comment by Ceeb182** [comment]
**FR /** correction d'une erreur trouvée par @mipel85 à la page 5 : orthographe "en s**é**lectionnant"
**EN /** fix an error found by @mipel85 on page 5: spelling "en s**é**lectionnant"

**Comment by Ceeb182** [comment]
Confirmation received by Email.
Work merged on **Next_release** branch
