### ISSUE TITLE
Redundancy bus - Manuel utilisateur - vPlus.Fr5.pdf / Corrections

### ISSUE THREAD

**Issue by mipel85** [Ceeb182/Nonofficial_frsky_doc#20]
I didn't forget to respect [contributing](https://github.com/Ceeb182/Nonofficial_frsky_doc/blob/master/CONTRIBUTING.MD) rules !
- [x] Correction
- [ ] New drawing
- [ ] New Literal translation
- [ ] Translation from an existing SVG file
- [ ] New news for `Plus` and `Unpublished` version
- [ ] Other...  

Message :
Redundancy bus - Manuel utilisateur - vPlus.Fr5.pdf -- proposed corrections

[Redundancy bus - Manuel utilisateur - vPlus.Fr5.pdf](https://github.com/Ceeb182/Nonofficial_frsky_doc/files/1450095/Redundancy.bus.-.Manuel.utilisateur.-.vPlus.Fr5.pdf)

**Comment by Ceeb182** [comment]
I saw your PDF. All your comments can be read : no problem. I'll begin to correct tonight.

**Comment by Ceeb182** [comment]
Voici le fichier corrigé / Here is the corrected file
[Redundancy bus - Manuel utilisateur - vPlus.Fr6.pdf](https://github.com/Ceeb182/Nonofficial_frsky_doc/files/1454133/Redundancy.bus.-.Manuel.utilisateur.-.vPlus.Fr6.pdf)


Note de version / Release note :
**Section en Français**
>- Section "Caractéristiques" :
>   * orthographe : "Caractéri**s**tiques", "gr**â**ce", 2x"rafra**î**ssement", "param**é**trable"  
>   * grammaire : "Compatible" sans "s"  
>- Section "Connexion" : 2x expression "qu'un" en "d'un"  
>- Section "Alimentation électrique" : expression "par une batterie **ou un** BEC", "contre les"  
>- Section "Protection contre les surcharges" : orthographe 5x"ambi**a**nt"  
>- Section "Configuration de OpenTx (...) télémétriques" : grammaire "doté**e**"  
>- Section "Description (...) RBCS et RBS" :  
>   * grammaire "doté**e**"  
>   * expression "un **un**"  
>   * orthographe "gr**â**ce"  
>- Section "Génération de capteurs virtuels" : grammaire "enregistre**z**-le"  

**English section** 
>- "Caractéristiques" section:
>   * spelling : "Caractéri**s**tiques", "gr**â**ce", 2x"rafra**î**ssement", "param**é**trable"  
>   * grammar : "Compatible" sans "s"  
>- "Connexion" section : 2x expression "qu'un" into "d'un"  
>- "Alimentation électrique" section : expression "par une batterie **ou un** BEC", "contre les"  
>- "Protection contre les surcharges" section : spelling 5x"ambi**a**nt"  
>- "Configuration de OpenTx (...) télémétriques" section : grammar "doté**e**"  
>- "Description (...) RBCS et RBS" section :  
>   * grammar "doté**e**"  
>   * expression "un **un**"  
>   * spelling "gr**â**ce"  
>- "Génération de capteurs virtuels" section : grammar "enregistre**z**-le"  

@mipel85 
**FR** / Je pense avoir tout corrigé. Peux-tu faire une vérification rapide ?
Si c'est Ok laisse quand même ouvert l'issue #20. Je la fermerai quand j'effectuerai le MERGE de la correction.
**EN** / I think I have corrected everything. Can you do a quick check ?
If it's Ok let's still open issue #20. I will close it when I perform the MERGE of the fix.

**Comment by Ceeb182** [comment]
Confirmation received by Email.
Work merged on **Next_release** branch
