### ISSUE TITLE
Redundancy bus - Procédure de mise à jour - vFr2.pdf / corrections

### ISSUE THREAD

**Issue by mipel85** [Ceeb182/Nonofficial_frsky_doc#21]
[Redundancy bus - Procédure de mise à jour - vFr2.pdf](https://github.com/Ceeb182/Nonofficial_frsky_doc/files/1466822/Redundancy.bus.-.Procedure.de.mise.a.jour.-.vFr2.pdf)
I didn't forget to respect [contributing](https://github.com/Ceeb182/Nonofficial_frsky_doc/blob/master/CONTRIBUTING.MD) rules !
- [x] Correction
- [ ] New drawing
- [ ] New Literal translation
- [ ] Translation from an existing SVG file
- [ ] New news for `Plus` and `Unpublished` version
- [ ] Other...  

Message : some others corrections of spelling errors

**Comment by Ceeb182** [comment]
Voici le fichier corrigé / Here is the corrected file
[Redundancy bus - Procédure de mise à jour - vFr3.pdf](https://github.com/Ceeb182/Nonofficial_frsky_doc/files/1470507/Redundancy.bus.-.Procedure.de.mise.a.jour.-.vFr3.pdf)

Note de version / Release note :
**Section en Français**
>- Grammaire "L**a** version"
>- Orthographe "l'autre **extrémité**", "Flash **external**"
>- Modification phrase : "vous référer à l'image ci-dessous"


**English section** 
>- Grammar "L**a** version"
>- Spelling "l'autre **extrémité**", "Flash **external**"
>- Sentence modification : "vous référer à l'image ci-dessous"

@mipel85 
**FR** / Je pense avoir tout corrigé. Peux-tu faire une vérification rapide ?
Si c'est Ok laisse quand même ouvert l'issue #21. Je la fermerai quand j'effectuerai le MERGE de la correction.
**EN** / I think I have corrected everything. Can you do a quick check ?
If it's Ok let's still open issue #21. I will close it when I perform the MERGE of the fix.

**Comment by Ceeb182** [comment]
Confirmation received by Email.
Work merged on **Next_release** branch
