### ISSUE TITLE
Mipel85 - Variomètre - Manuel utilisateur - vFr3.pdf

### ISSUE THREAD

**Issue by mipel85** [Ceeb182/Nonofficial_frsky_doc#23]
I didn't forget to respect [contributing](https://github.com/Ceeb182/Nonofficial_frsky_doc/blob/master/CONTRIBUTING.MD) rules !
- [x] Correction
- [ ] New drawing
- [ ] New Literal translation
- [ ] Translation from an existing SVG file
- [ ] New news for `Plus` and `Unpublished` version
- [ ] Other...  

Message :
some spelling corrections
[Variomètre - Manuel utilisateur - vFr3.pdf](https://github.com/Ceeb182/Nonofficial_frsky_doc/files/1509803/Variometre.-.Manuel.utilisateur.-.vFr3.pdf)

**Comment by Ceeb182** [comment]
**EN /** No problem to see things to fix. I do that as soon as possible.
**FR /** Aucun problème pour visualiser les éléments à modifier. Je fais cela dès que possible.

**Comment by Ceeb182** [comment]
Voici le fichier corrigé / Here is the corrected file
[Variomètre - Manuel utilisateur - vFr4 - Ceeb182.pdf](https://github.com/Ceeb182/Nonofficial_frsky_doc/files/1552961/Variometre.-.Manuel.utilisateur.-.vFr4.-.Ceeb182.pdf)


Note de version / Release note :
**Section en Français**
>- Suppression de la majuscule de "Variométrique" x8
>- Paragraphe "Nouveauté" : changement point virgule en virgule
>- Paragraphe 4.2 : orthographe "câbles"
>- Dernier paragraphe "Avertissement" : grammaire "peuvent" en "peut"

**English section** 
>- Removing the capital letter of "Variométrique" x8
>- "Nouveauté" section : change semicolon to comma
>- 4.2 section : spelling "câbles"
>- "Avertissement" in last section : grammar "peuvent" into "peut"

@mipel85 
**FR** / Je pense avoir tout corrigé. Peux-tu faire une vérification rapide ?
Si c'est Ok laisse quand même ouvert l'issue #23. Je la fermerai quand j'effectuerai le MERGE de la correction.
**EN** / I think I have corrected everything. Can you do a quick check ?
If it's Ok let's still open issue #23. I will close it when I perform the MERGE of the fix.

**Comment by Ceeb182** [comment]
**FR /** Mail de mipel85 : orthographe de "variométrique" corrigé dans le paragraphe "Spécifications"
**EN /** Mail from mipel85 : Spelling of "variométrique" fixed in "Spécifications" section.

**Comment by mipel85** [comment]
Bon pour moi / Ok for me

**Comment by Ceeb182** [comment]
Merged in **Next_release** branch.
