### ISSUE TITLE
SCC - Manuel utilisateur - vFr2.pdf

### ISSUE THREAD

**Issue by mipel85** [Ceeb182/Nonofficial_frsky_doc#24]
I didn't forget to respect [contributing](https://github.com/Ceeb182/Nonofficial_frsky_doc/blob/master/CONTRIBUTING.MD) rules !
- [x] Correction
- [ ] New drawing
- [ ] New Literal translation
- [ ] Translation from an existing SVG file
- [ ] New news for `Plus` and `Unpublished` version
- [ ] Other...  

Message :
some spelling corrections
[SCC - Manuel utilisateur - vFr2.pdf](https://github.com/Ceeb182/Nonofficial_frsky_doc/files/1509844/SCC.-.Manuel.utilisateur.-.vFr2.pdf)

**Comment by Ceeb182** [comment]
**EN /** No problem to see things to fix. I do that as soon as possible.
**FR /** Aucun problème pour visualiser les éléments à modifier. Je fais cela dès que possible.

**Comment by Ceeb182** [comment]
Voici le fichier corrigé / Here is the corrected file
[SCC - Manuel utilisateur - vFr3-Ceeb182.pdf](https://github.com/Ceeb182/Nonofficial_frsky_doc/files/1553286/SCC.-.Manuel.utilisateur.-.vFr3-Ceeb182.pdf)

Note de version / Release note :
**Section en Français**
>- Grammaire : "tel qu'indiqué", "les servos compatibles" 

**English section** 
>- Grammar : "tel qu'indiqué", "les servos compatibles"

@mipel85 
**FR** / Je pense avoir tout corrigé. Peux-tu faire une vérification rapide ?
Si c'est Ok laisse quand même ouvert l'issue #24. Je la fermerai quand j'effectuerai le MERGE de la correction.
**EN** / I think I have corrected everything. Can you do a quick check ?
If it's Ok let's still open issue #24. I will close it when I perform the MERGE of the fix.

**Comment by mipel85** [comment]
Bon pour moi / Ok for me

**Comment by Ceeb182** [comment]
Merged in **Next_release** branch
