### ISSUE TITLE
X8R - Manuel utilisateur - vFr5.pdf + X8R - Manuel utilisateur - vPlus.Fr3.pdf

### ISSUE THREAD

**Issue by mipel85** [Ceeb182/Nonofficial_frsky_doc#26]
I didn't forget to respect [contributing](https://github.com/Ceeb182/Nonofficial_frsky_doc/blob/master/CONTRIBUTING.MD) rules !
- [x] Correction
- [ ] New drawing
- [ ] New Literal translation
- [ ] Translation from an existing SVG file
- [ ] New news for `Plus` and `Unpublished` version
- [ ] Other...  

Message :
some spelling corrections
[X8R - Manuel utilisateur - vFr5.pdf](https://github.com/Ceeb182/Nonofficial_frsky_doc/files/1510780/X8R.-.Manuel.utilisateur.-.vFr5.pdf)
[X8R - Manuel utilisateur - vPlus.Fr3.pdf](https://github.com/Ceeb182/Nonofficial_frsky_doc/files/1510781/X8R.-.Manuel.utilisateur.-.vPlus.Fr3.pdf)

**Comment by Ceeb182** [comment]
**EN /** No problem to see things to fix. I do that as soon as possible.
**FR /** Aucun problème pour visualiser les éléments à modifier. Je fais cela qès que possible.

**Comment by Ceeb182** [comment]
Voici les fichiers corrigés / Here is the corrected files
[X8R - Manuel utilisateur - vFr6-Ceeb182.pdf](https://github.com/Ceeb182/Nonofficial_frsky_doc/files/1557235/X8R.-.Manuel.utilisateur.-.vFr6-Ceeb182.pdf)
[X8R - Manuel utilisateur - vPlus.Fr4-Ceeb182.pdf](https://github.com/Ceeb182/Nonofficial_frsky_doc/files/1557237/X8R.-.Manuel.utilisateur.-.vPlus.Fr4-Ceeb182.pdf)


Note de version / Release note :
**Section en Français**
>**vBase** : orthographe "Impulsion" x2, "relâcher", "clignote", "récepteur", "brièvement" x3  
>**vPlus** : orthographe : "Impulsion" x2, "brièvement" x2 et phrase : "Ceci permet de lier"  

**English section** 
>**vBase** : spelling "Impulsion" x2, "relâcher", "clignote", "récepteur", "brièvement" x3  
>**vPlus** : spelling : "Impulsion" x2, "brièvement" x2 and sentence : "Ceci permet de lier"  

@mipel85 
**FR** / Je pense avoir tout corrigé. Peux-tu faire une vérification rapide ?
Si c'est Ok laisse quand même ouvert l'issue #26. Je la fermerai quand j'effectuerai le MERGE de la correction.
**EN** / I think I have corrected everything. Can you do a quick check ?
If it's Ok let's still open issue #26. I will close it when I perform the MERGE of the fix.

**Comment by mipel85** [comment]
Bon pour moi / Ok for me

**Comment by Ceeb182** [comment]
Merged in **Next_release** branch
