### ISSUE TITLE
Receiver - R-XSR / New FR translation in "Base" version

### ISSUE THREAD

**Issue by Ceeb182** [Ceeb182/Nonofficial_frsky_doc#28]
- [x] New translation from original FrSky document

*Message :*
I begin to work on new French translation in "**Base**" version of R-XSR receiver.
I use "**R-XSR - User Manual vEN 2017-09-01.pdf**" as origin from https://www.frsky-rc.com.

**Comment by Ceeb182** [comment]
**FR** / @mipel85 
Voici la traduction `vBase` FR du manuel du récepteur R-XSR.
Peux-tu vérifier que tout est ok ?

**EN** / @mipel85 
Here is the `vBase` FR translation of the R-XSR receiver manual.
Can you check that everything is ok?

[R-XSR - Manuel utilisateur - vFr1.pdf](https://github.com/Ceeb182/Nonofficial_frsky_doc/files/1583377/R-XSR.-.Manuel.utilisateur.-.vFr1.pdf)

**Comment by mipel85** [comment]
Bon pour moi / Ok for me

**Comment by Ceeb182** [comment]
Thank. Now I will prepare the next release.

**Comment by Ceeb182** [comment]
Merged in **Next_release** branch
