### ISSUE TITLE
Receiver - XM / New FR translation in "Base" version

### ISSUE THREAD

**Issue by Ceeb182** [Ceeb182/Nonofficial_frsky_doc#3]
I begin to work on new French translation in "**Base**" version of XM receiver.
I use "**XM - User manual - vEN 2016-11-21.pdf**" as origin from https://www.frsky-rc.com.

**Comment by Ceeb182** [comment]
The first release of **XM - Manuel utilisateur - vFr1** is done in the **Next_release** branch.
@mipel85, I leave issue #3 open to show that this document has not yet been re-read.

**Comment by mipel85** [comment]
Document validé après relecture

**Comment by Ceeb182** [comment]
Ok, doc checked. Ready for next release.
