### ISSUE TITLE
Receiver - X4R X4RSB / New FR translation in "Base" version

### ISSUE THREAD

**Issue by Ceeb182** [Ceeb182/Nonofficial_frsky_doc#31]
- [x] Complete translation both on the substance and on the form

*Message :*
I begin to work on new French translation in "**Base**" version of X4R/X4RSB receiver.
I use "**X4R X4RSB - User manual - vEN 2016-06-12.pdf**" as origin from https://www.frsky-rc.com.

**Comment by Ceeb182** [comment]
**FR** / @mipel85
Voici la traduction `vBase` FR du manuel du récepteur X4R/X4RSB.
Peux-tu vérifier que tout est ok ?

**EN** / @mipel85 
Here is the `vBase` FR translation of the X4R/X4RSB receiver manual.
Can you check that everything is ok?

[X4R X4RSB - Manuel utilisateur - vFr1.pdf](https://github.com/Ceeb182/Nonofficial_frsky_doc/files/1681986/X4R.X4RSB.-.Manuel.utilisateur.-.vFr1.pdf)

**Comment by mipel85** [comment]
corrections de fautes d'orthographe / some spelling corrections
[X4R.X4RSB.-.Manuel.utilisateur.-.vFr1.pdf](https://github.com/Ceeb182/Nonofficial_frsky_doc/files/1682152/X4R.X4RSB.-.Manuel.utilisateur.-.vFr1.pdf)

**Comment by Ceeb182** [comment]
Wow ! What speed ! I will try to be as quick in updating the translation.
Wahou ! Quelle rapidité ! Je vais essayer d'être aussi rapide dans la mise à jour de la traduction.

**Comment by Ceeb182** [comment]
[X4R X4RSB - Manuel utilisateur - vFr1 - Ceeb182.pdf](https://github.com/Ceeb182/Nonofficial_frsky_doc/files/1682586/X4R.X4RSB.-.Manuel.utilisateur.-.vFr1.-.Ceeb182.pdf)

Translation fixed ! Now I will prepare the next release.
Traduction corrigée ! Maintenant je vais préparer la prochaine publication.

**Comment by Ceeb182** [comment]
Merged in _Next_release_ branch
