### ISSUE TITLE
Receiver - XSR-M / New FR translation in "Base" version

### ISSUE THREAD

**Issue by Ceeb182** [Ceeb182/Nonofficial_frsky_doc#35]
- [x] Complete translation both on the substance and on the form

*Message :*
I begin to work on new French translation in "**Base**" version of XSR-M receiver.
I use "**XSR-M  - User manual - vEN 2017-07-12.pdf**" as origin from https://www.frsky-rc.com.

**Comment by Ceeb182** [comment]
**FR** / @mipel85
Voici la traduction `vBase` FR du manuel du récepteur XSR-M.
Peux-tu vérifier que tout est ok ?

**EN** / @mipel85 
Here is the `vBase` FR translation of the XSR-M  receiver manual.
Can you check that everything is ok?

[XSR-M - Manuel utilisateur - vFr1.pdf](https://github.com/Ceeb182/Nonofficial_frsky_doc/files/1838942/XSR-M.-.Manuel.utilisateur.-.vFr1.pdf)

**Comment by mipel85** [comment]
Bon pour moi / Ok for me

**Comment by Ceeb182** [comment]
Merci. Je vais mettre à jour le QR code et préparer cette branche pour la prochaine version.
Thank you. I will update the QR Code and prepare this branch for the next release.

**Comment by Ceeb182** [comment]
**FR /** C'est fait. Prêt à être fusionné dans la branche Next_release.
**EN /** It's done. Ready to be merged into the Next_release branch.

**Comment by Ceeb182** [comment]
Done !
