### ISSUE TITLE
Receiver - XMR / New FR and EN doc "How to update firmware" in "Unpublished" version

### ISSUE THREAD

**Issue by Ceeb182** [Ceeb182/Nonofficial_frsky_doc#36]
- [x] Complete "unpublished" doc both on the substance and on the form

*Message :*
I begin to work on new French and English document in "**Unpublished**" version titled "**How to update firmware for FrSky XMR receiver**".
I use these weblinks to create this document :
- https://www.rcgroups.com/forums/showthread.php?2833076-FrSky-New-Arrival-XMR/page2  
- https://www.unmannedtechshop.co.uk/frsky-xmr-mini-6ch-pwm-receiver/
- http://frskytaranis.forumactif.org/t4948-xmr-recepteur-x-indoor#58765
- http://frskytaranis.forumactif.org/t4948-xmr-recepteur-x-indoor#58194
- https://www.youtube.com/watch?v=qzzUtFIcqM0&t=168s#

**Comment by Ceeb182** [comment]
**FR** / @mipel85
Voici le nouveau document inédit en **français**. 
Il s'agit de la procédure de mise à jour du firmware du récepteur XMR.
Peux-tu vérifier que tout est ok ?

**EN** / @mipel85 
Here is the new unpublished document in **French**. 
This is the firmware update procedure for the XMR receiver.
Can you check that everything is ok?

[XMR - MaJ Firmware - vInédit.Fr1.pdf](https://github.com/Ceeb182/Nonofficial_frsky_doc/files/1842973/XMR.-.MaJ.Firmware.-.vInedit.Fr1.pdf)

**Comment by Ceeb182** [comment]
**FR** / @LapinFou
Voici le nouveau document inédit en **anglais**. 
Il s'agit de la procédure de mise à jour du firmware du récepteur XMR.
Peux-tu vérifier que tout est ok ?

**EN** / @LapinFou 
Here is the new unpublished document in **English**. 
This is the firmware update procedure for the XMR receiver.
Can you check that everything is ok?

[XMR - Firmware Update - vUnpublished.En1.pdf](https://github.com/Ceeb182/Nonofficial_frsky_doc/files/1842983/XMR.-.Firmware.Update.-.vUnpublished.En1.pdf)

**Comment by LapinFou** [comment]
[XMR.-.Firmware.Update.-.vUnpublished.En2.pdf](https://github.com/Ceeb182/Nonofficial_frsky_doc/files/1845451/XMR.-.Firmware.Update.-.vUnpublished.En2.pdf)

Here is a corrected version of this documentation.

**Comment by Ceeb182** [comment]
Voici le fichier corrigé / Here is the corrected file
[XMR - Firmware Update - vUnpublished.En1Rev2.pdf](https://github.com/Ceeb182/Nonofficial_frsky_doc/files/1845693/XMR.-.Firmware.Update.-.vUnpublished.En1Rev2.pdf)

@LapinFou 
**FR** / Je pense avoir tout corrigé. Peux-tu faire une vérification rapide ?
**EN** / I think I have corrected everything. Can you do a quick check ?

**Comment by mipel85** [comment]
corrections de fautes d'orthographe / some spelling corrections
[XMR.-.MaJ.Firmware.-.vInedit.Fr1.pdf](https://github.com/Ceeb182/Nonofficial_frsky_doc/files/1847607/XMR.-.MaJ.Firmware.-.vInedit.Fr1.pdf)

**Comment by LapinFou** [comment]
Few more corrections.
Shall we speak in French or English on the Git repo??
[XMR.-.Firmware.Update.-.vUnpublished.En1Rev2.pdf](https://github.com/Ceeb182/Nonofficial_frsky_doc/files/1847746/XMR.-.Firmware.Update.-.vUnpublished.En1Rev2.pdf)

**Comment by LapinFou** [comment]
Pour la version Française, même remarque que pour la version US. Je pense que l'étape 3 et 7 ne sont par correct pour la procédure de mise à jour.

**Comment by Ceeb182** [comment]
**FR** / Il est convenu avec FrSky que les messages, notes de versions et fichiers explicatifs (README.MD, CONTRIBUTING.MD...) soient en langue anglaise pour pouvoir suivre et/ou intervenir en cas de besoin.
Comme nos lecteurs principaux actuels sont français, je fais l'effort d'écrire les messages dans les deux langues. Je ne voudrais pas décourager nos contributeurs francophones.
Pour simplifier, la langue anglaise est obligatoire, la langue française est facultative.
En ce qui concerne le document français, je vais modifier les étapes 3 et 7.

**EN** / It is agreed with FrSky that messages, release notes and explanatory files (README.MD, CONTRIBUTING.MD...) are in English to be able to follow and/or intervene if necessary.
As our current main readers are French, I make the effort to write the messages in both languages. I would not want to discourage our francophone contributors.
To simplify, the English language is mandatory, the French language is optional.
About French document, I will modify steps 3 and 7.

**Comment by LapinFou** [comment]
OK. Thanks for the clarification. 😄

**Comment by mipel85** [comment]
@LapinFou : 
> Je pense que l'étape 3 et 7 ne sont par correct pour la procédure de mise à jour.

Qu'est-ce qui te semble incorrect dans ces deux étapes ?

**Comment by Ceeb182** [comment]
**FR /** A l'étape 3, il est inutile de brancher le XMR. Le XMR ne se branche qu'à l'étape 7.
C'est [la vidéo FrSky](https://www.youtube.com/watch?v=qzzUtFIcqM0&t=168s#) (à 4mn23s) qui m'avait poussé à indiquer le branchement du XMR à l'étape 3. A l'époque, quand j'ai écrit cette documentation je n'avais jamais fait par moi-même une mise à jour d'un firmware avec un PC. C'est toujours compliqué de faire une synthèse d'informations (parfois contradictoires) se trouvant sur la toile et de ne pas pouvoir tester soi-même sa doc faute de matériel.
Cependant, depuis que j'ai mis à jour des firmwares avec l'outil USB STK et un récepteur S8R, il me semble tout à fait logique de n'effectuer ce branchement qu'à l'étape 7. 

**EN /** In step 3, there is no need to connect the XMR. The XMR only connects in step 7.
It was [the FrSky video](https://www.youtube.com/watch?v=qzzUtFIcqM0&t=168s#) (at 4mn23s) that made me indicate the connection of the XMR in step 3. At the time, when I wrote this documentation I had never done by myself a firmware update with a PC. It's always complicated to make a synthesis of information (sometimes contradictory) on the web and not to be able to test yourself your doc for lack of material.
However, since I updated firmwares with the USB STK tool and an S8R receiver, it seems quite logical to me to make this connection only in step 7.

**Comment by Ceeb182** [comment]
Voici le nouveau fichier corrigé (En1.Rev3) / Here is the new corrected file (En1.Rev3)
[XMR - Firmware Update - vUnpublished.En1Rev3.pdf](https://github.com/Ceeb182/Nonofficial_frsky_doc/files/1851008/XMR.-.Firmware.Update.-.vUnpublished.En1Rev3.pdf)

@LapinFou 
**FR** / Je pense avoir tout corrigé. Peux-tu faire une vérification rapide ?
**EN** / I think I have corrected everything. Can you do a quick check ?

**Comment by Ceeb182** [comment]
Voici le nouveau fichier corrigé (Fr1.Rev2) / Here is the new corrected file (Fr1.Rev2)
[XMR - MaJ Firmware - vInédit.Fr1Rev2.pdf](https://github.com/Ceeb182/Nonofficial_frsky_doc/files/1851180/XMR.-.MaJ.Firmware.-.vInedit.Fr1Rev2.pdf)

@mipel85 
**FR** / Je pense avoir tout corrigé. Peux-tu faire une vérification rapide ?
**EN** / I think I have corrected everything. Can you do a quick check ?

**Comment by LapinFou** [comment]
Here are the last corrections. After that it should be all good.
[XMR.-.Firmware.Update.-.vUnpublished.En1Rev3.pdf](https://github.com/Ceeb182/Nonofficial_frsky_doc/files/1851195/XMR.-.Firmware.Update.-.vUnpublished.En1Rev3.pdf)

**Comment by Ceeb182** [comment]
Voici le nouveau fichier corrigé (En1.Rev4) / Here is the new corrected file (En1.Rev4)
[XMR - Firmware Update - vUnpublished.En1Rev4.pdf](https://github.com/Ceeb182/Nonofficial_frsky_doc/files/1851365/XMR.-.Firmware.Update.-.vUnpublished.En1Rev4.pdf)

@LapinFou 
**FR** / Je pense avoir tout corrigé. Peux-tu faire une vérification rapide ?
**EN** / I think I have corrected everything. Can you do a quick check ?

**Comment by LapinFou** [comment]
Last one:
`PC running Windows 7 (or above), when plugged`
should be
`PC running Windows 7 (or above) when plugged`
The comma is unnecessary.

Except this last typo, it is all fine for me.
Maybe you may contact British/US guy for a final read?

**Comment by Ceeb182** [comment]
It's a good idea but I don't know anyone English/American.
Anyway, thanks for all the proofreading. There was a lot to correct in the English version.

[XMR - Firmware Update - vUnpublished.En1Rev5.pdf](https://github.com/Ceeb182/Nonofficial_frsky_doc/files/1851426/XMR.-.Firmware.Update.-.vUnpublished.En1Rev5.pdf)

**Comment by LapinFou** [comment]
You're welcome.

**Comment by Ceeb182** [comment]
@mipel85 
Tu n'as pas du recevoir la notification GitHub / You must not have received the GitHub notification
Voici le nouveau fichier corrigé (Fr1.Rev2) / Here is the new corrected file (Fr1.Rev2)
[XMR - MaJ Firmware - vInédit.Fr1Rev2.pdf](https://github.com/Ceeb182/Nonofficial_frsky_doc/files/1851180/XMR.-.MaJ.Firmware.-.vInedit.Fr1Rev2.pdf)

Je pense avoir tout corrigé. Peux-tu faire une vérification rapide ? / I think I have corrected everything. Can you do a quick check ?

**Comment by mipel85** [comment]
Rev2:
Bon pour moi / Ok for me

**Comment by Ceeb182** [comment]
Done !
