### ISSUE TITLE
Module - R9M Tx EU / New FR translation in "Base" version

### ISSUE THREAD

**Issue by Ceeb182** [Ceeb182/Nonofficial_frsky_doc#39]
- [x] Complete translation both on the substance and on the form

*Message :*
I begin to work on new French translation in "**Base**" version of R9M Tx EU module.
I use "**R9M EU - User Manual - vEN 2018-05-03.pdf**" as origin from https://www.frsky-rc.com.

**Comment by Ceeb182** [comment]
**FR** / @mipel85
Voici la traduction `vBase` FR du manuel du module d'émission longue portée R9M.
Peux-tu vérifier que tout est ok ?

**EN** / @mipel85 
Here is the `vBase` FR translation of the long range R9M transmitter module.
Can you check that everything is ok?

[R9M Tx EU - Manuel utilisateur - vFr1.pdf](https://github.com/Ceeb182/Nonofficial_frsky_doc/files/2002442/R9M.Tx.EU.-.Manuel.utilisateur.-.vFr1.pdf)

**Comment by mipel85** [comment]
corrections de fautes d'orthographe / some spelling corrections
[R9M.Tx.EU.-.Manuel.utilisateur.-.vFr1_backup.pdf](https://github.com/Ceeb182/Nonofficial_frsky_doc/files/2016256/R9M.Tx.EU.-.Manuel.utilisateur.-.vFr1_backup.pdf)

**Comment by mipel85** [comment]
corrections de fautes d'orthographe / some spelling corrections
[R9M.Tx.EU.-.Manuel.utilisateur.-.vFr1.pdf](https://github.com/Ceeb182/Nonofficial_frsky_doc/files/2016261/R9M.Tx.EU.-.Manuel.utilisateur.-.vFr1.pdf)

**Comment by Ceeb182** [comment]
Voici le nouveau fichier corrigé (Fr1.Rev2) / Here is the new corrected file (Fr1.Rev2)
[R9M Tx EU - Manuel utilisateur - vFr1.Rev2.pdf](https://github.com/Ceeb182/Nonofficial_frsky_doc/files/2039083/R9M.Tx.EU.-.Manuel.utilisateur.-.vFr1.Rev2.pdf)

@mipel85  
**FR** / Je pense avoir tout corrigé. Peux-tu faire une vérification rapide ?
**EN** / I think I have corrected everything. Can you do a quick check ?

**Comment by mipel85** [comment]
Bon pour moi / Ok for me

**Comment by Ceeb182** [comment]
Ready for next release.
