### ISSUE TITLE
Receiver - R9 Slim / New FR translation in "Base" version

### ISSUE THREAD

**Issue by Ceeb182** [Ceeb182/Nonofficial_frsky_doc#43]
- [x] Complete translation both on the substance and on the form

*Message :*
I begin to work on new French translation in "**Base**" version of R9Slim receiver.
I use "**R9Slim - User Manual - vEN 2018-02-06.pdf**" as origin from https://www.frsky-rc.com.

**Comment by Ceeb182** [comment]
**FR** / @mipel85
Voici la traduction `vBase` FR du manuel du récepteur longue portée **R9 Slim**.
Peux-tu vérifier que tout est ok ?

**EN** / @mipel85 
Here is the `vBase` FR translation of the long range **R9 Slim** receiver.
Can you check that everything is ok?

[R9 Slim - Manuel utilisateur - vFr1.pdf](https://github.com/Ceeb182/Nonofficial_frsky_doc/files/2120799/R9.Slim.-.Manuel.utilisateur.-.vFr1.pdf)

**Comment by mipel85** [comment]
Bon pour moi / Ok for me

**Comment by Ceeb182** [comment]
Ready for next release.
