### ISSUE TITLE
Receiver - R9 Mini / New FR translation in "Base" version

### ISSUE THREAD

**Issue by Ceeb182** [Ceeb182/Nonofficial_frsky_doc#45]
- [x] Complete translation both on the substance and on the form

*Message :*
I begin to work on new French translation in "**Base**" version of R9Mini receiver.
I use "**R9 Mini - User Manual vEN 2018-05-16.pdf**" as origin from https://www.frsky-rc.com.

**Comment by Ceeb182** [comment]
**FR** / @mipel85
Voici la traduction `vBase` FR du manuel du récepteur longue portée **R9 Mini**.
Peux-tu vérifier que tout est ok ?

**EN** / @mipel85 
Here is the `vBase` FR translation of the long range **R9 Mini** receiver.
Can you check that everything is ok?

[R9 Mini - Manuel utilisateur - vFr1.pdf](https://github.com/Ceeb182/Nonofficial_frsky_doc/files/2125594/R9.Mini.-.Manuel.utilisateur.-.vFr1.pdf)

**Comment by mipel85** [comment]
Bon pour moi / Ok for me

**Comment by Ceeb182** [comment]
Ready for next release.
