### ISSUE TITLE
Module - R9M Lite LBT / New FR translation in "Base" version

### ISSUE THREAD

**Issue by Ceeb182** [Ceeb182/Nonofficial_frsky_doc#47]
- [x] Complete translation both on the substance and on the form

*Message :*
I begin to work on new French translation in "**Base**" version of R9M Lite LBT module.
I use "**R9M Lite LBT - User Manual vEN 2018-05-16.pdf**" as origin from https://www.frsky-rc.com.

**Comment by Ceeb182** [comment]
**FR** / @mipel85
Voici la traduction `vBase` FR du manuel du module d'émission longue portée `R9M Lite LBT`.
Peux-tu vérifier que tout est ok ?

**EN** / @mipel85 
Here is the `vBase` FR translation of the long range `R9M Lite LBT` transmitter module.
Can you check that everything is ok?

[R9M Lite LBT - Manuel utilisateur - vFr1.pdf](https://github.com/Ceeb182/Nonofficial_frsky_doc/files/2131253/R9M.Lite.LBT.-.Manuel.utilisateur.-.vFr1.pdf)

**Comment by mipel85** [comment]
Bon pour moi / Ok for me

**Comment by Ceeb182** [comment]
Ready for next release.
