### ISSUE TITLE
Receiver - RX8R Pro / New FR translation in "Base" version

### ISSUE THREAD

**Issue by Ceeb182** [Ceeb182/Nonofficial_frsky_doc#48]
- [x] Complete translation both on the substance and on the form

*Message :*
I begin to work on new French translation in "**Base**" version of **RX8R Pro** receiver.
I use "**RX8R PRO-Manual vEN 2018-03-07.pdf**" as origin from https://www.frsky-rc.com.

**Comment by Ceeb182** [comment]
**FR** / @mipel85
Voici la traduction `vBase` FR du manuel du récepteur **RX8R Pro**.
Peux-tu vérifier que tout est ok ?

**EN** / @mipel85 
Here is the `vBase` FR translation of the **RX8R Pro** receiver.
Can you check that everything is ok?

[RX8R Pro - Manuel utilisateur - vFr1.pdf](https://github.com/Ceeb182/Nonofficial_frsky_doc/files/2343463/RX8R.Pro.-.Manuel.utilisateur.-.vFr1.pdf)

**Comment by mipel85** [comment]
corrections de fautes d'orthographe / some spelling corrections
[RX8R.Pro.-.Manuel.utilisateur.-.vFr1.pdf](https://github.com/Ceeb182/Nonofficial_frsky_doc/files/2352178/RX8R.Pro.-.Manuel.utilisateur.-.vFr1.pdf)

**Comment by Ceeb182** [comment]
[RX8R Pro - Manuel utilisateur - vFr1.Rev2.pdf](https://github.com/Ceeb182/Nonofficial_frsky_doc/files/2362569/RX8R.Pro.-.Manuel.utilisateur.-.vFr1.Rev2.pdf)

Translation fixed ! Now I will prepare the next release.

**Comment by Ceeb182** [comment]
Done !
