### ISSUE TITLE
Receiver - XMR / New FR translation in "Base" version

### ISSUE THREAD

**Issue by Ceeb182** [Ceeb182/Nonofficial_frsky_doc#8]
I begin to work on new French translation in "**Base**" version of XMR receiver.
I use "**XMR - User Manual -vEN 2017-02-08.pdf**" as origin from https://www.frsky-rc.com.

**Comment by Ceeb182** [comment]
The first release of **XMR - Manuel utilisateur - vFr1** is done in the **Next_release** branch.
@mipel85, I leave issue #8 open to show that this document has not yet been re-read.

**Comment by mipel85** [comment]
corrigé dans le dernier encadré: ... que vous posséde**z** (et non posséder) la dernière mise à jour du micro.

**sinon à voir:**
.1 Pour les Taranis X9D/X9D Plus/X9E et la Taranis Q X7, mettre en marche l'émetteur, aller dans  MENU - CONFIGURATION           MODELE - PAGE 2, **choisir HF Interne ou Externe**, et sélectionner BIND. 
choisir Interne ou Externe ne demanderait pas à être expliqué ?
**et ici point 4:**
La LED verte sur le récepteur indique que le récepteur reçoit les commandes issues de l'émetteur.
à modifier en:
La LED verte sur le récepteur indique qu'il reçoit les commandes issues de l'émetteur.

**Comment by Ceeb182** [comment]
- Grammar error "vous possédez" : done in the last #8 commit 
- For the two other remarks "HF interne ou Externe" and "Point 4" of "binding procedure" : they will correct on the next "Plus" version of this document.  

Thank you for this proofreading

**Comment by Ceeb182** [comment]
For the "Base" version, everything is up to date!
